package com.guille.gestures;

public class Enums {
	public enum Gesture {
		ARRIBA_IZQUIERDA, ARRIBA, ARRIBA_DERECHA, IZQUIERDA, CENTRO, DERECHA, ABAJO_DERECHA, ABAJO, ABAJO_IZQUIERDA, ARRIBA_LEJOS, ABAJO_LEJOS, IZQUIERDA_LEJOS, 
		DERECHA_LEJOS, ARRIBA_DERECHA_LEJOS, ARRIBA_IZQUIERDA_LEJOS, ABAJO_DERECHA_LEJOS, ABAJO_IZQUIERDA_LEJOS
	}
	
	public enum Tecla { //TODO poner símbolos
		A, B, C, D, E, F, G, H, I, J, K, L, M, N, Ñ, O, P, Q, R, S, T, U, V, W, X, Y, Z, NUM_0, NUM_1, NUM_2, NUM_3, NUM_4, NUM_5, NUM_6, 
		NUM_7, NUM_8, NUM_9, BORRAR, ESPACIO, FLECHA_IZQ, FLECHA_DER, FLECHA_ARR, FLECHA_AB, OPCIONES, ENTER, ESCAPE
	}
	
	
}
